package com.youmeek.ssm.manage.mapper;


import com.youmeek.ssm.manage.pojo.SysUser;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    SysUser selectByPrimaryKey(Long sysUserId);

    /**
     * 不指定字段模糊查询
     *
     * @param fields
     * @param searchText 查询条件
     * @return 用户实体列表
     */
    List<SysUser> getByFields(@Param("fields") List<String> fields, @Param("searchText") String searchText);

    /**
     * 指定字段模糊查询
     * @param field 字段名
     * @param searchText 查询条件
     * @return 用户实体列表
     */
    List<SysUser> getByField(@Param("field")String field, @Param("searchText")String searchText);

    /**
     * 查询所有用户列表
     * @return 用户列表
     */
    List<SysUser> getAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUser record);

    @Select("select column_name ,data_type,column_comment,0,0,character_maximum_length,is_nullable nullable\n" +
            "    from information_schema.columns where table_name = #{table_name} and table_schema = #{db_name}")
    List<String> selectFields(@Param("table_name") String table_name,@Param("db_name") String db_name);
}